export type Category = {
  id: number;
  name: string;
  color: string;
  text_color: string;
  slug: string;
  topic_count: number;
  post_count: number;
  position: number;
  description: string | null;
  description_text: string | null;
  description_excerpt: string | null;
  topic_url: string | null;
  read_restricted: boolean;
  permission: number;
  notification_level: number;
  can_edit: boolean;
  topic_template: string | null;
  has_children: boolean;
  subcategory_count: number | null;
  sort_order: string | null;
  sort_ascending: string | null;
  show_subcategory_list: boolean;
  num_featured_topics: number;
  default_view: string | null;
  subcategory_list_style: string;
  default_top_period: string;
  default_list_filter: string;
  minimum_required_tags: number;
  navigate_to_first_post_after_read: boolean;
  topics_day: number;
  topics_week: number;
  topics_month: number;
  topics_year: number;
  topics_all_time: number;
  is_uncategorized?: boolean | undefined;
  subcategory_ids: unknown[];
  subcategory_list?: Category[];
  uploaded_logo: string | null;
  uploaded_logo_dark: string | null;
  uploaded_background: string | null;
  uploaded_background_dark: string | null;
};

export type ReponseListTopics = {
  users: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
  }[];
  primary_group: {
    id: number;
    name: string;
    avatar_template: string;
  };
  topic_list: {
    can_create_topic: boolean;
    more_topics_url?: string | null;
    per_page: number;
    top_tags: string[];
    topics: Topic[];
  };
};

export type Topic = {
  id: number;
  title: string;
  fancy_title: string;
  slug: string;
  posts_count: number;
  reply_count: number;
  highest_post_number: number;
  image_url: string | null;
  created_at: string;
  last_posted_at: string;
  bumped: boolean;
  bumped_at: string;
  archetype: string;
  unseen: boolean;
  pinned: boolean;
  unpinned: string | null;
  excerpt: string;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  bookmarked: string | null;
  liked: string | null;
  views: number;
  like_count: number;
  has_summary: boolean;
  last_poster_username: string;
  category_id: number;
  pinned_globally: boolean;
  featured_link: string | null;
  posters: Array<{
    extras: string;
    description: string;
    user_id: number;
    primary_group_id: number | null;
  }>;
};

export type Reaction = {
  id: number;
  user_id: number;
  post_id: number;
  created_at: string;
  user: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
    title: string;
    primary_group_name: string | null;
  };
  post: {
    excerpt: string;
    truncated: boolean;
    id: number;
    created_at: string;
    title: string;
    url: string;
    category_id: number;
    post_number: number;
    topic_id: number;
    post_type: number;
    user: {
      id: number;
      username: string;
      name: string;
      avatar_template: string;
      title: string;
      primary_group_name: string | null;
    };
    topic: {
      id: number;
      title: string;
      fancy_title: string;
      slug: string;
      posts_count: number;
    };
  };
  reaction: {
    id: number;
    post_id: number;
    reaction_type: string;
    reaction_value: string;
    reaction_users_count: number;
    created_at: string;
  };
};

export type Invite = {
  id: number;
  redeemed_at: string;
  user: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
    topics_entered: number;
    posts_read_count: number;
    last_seen_at: string;
    time_read: number;
    days_visited: number;
    days_since_created: number;
  };
  invite_source: string;
};

export type DiscourseWebhook = {
  category?: CategoryWebhook;
  topic?: TopicWebhook;
  post?: PostWebhook;
  user?: UserWebhook;
  like?: PostLikedWebhook;
  user_badge?: UserBadgeWebhook;
};

export type CategoryWebhook = {
  id: number;
  name: string;
  color: string;
  text_color: string;
  slug: string;
  topic_count: number;
  post_count: number;
  position: number;
  description: string | null;
  description_text: string | null;
  description_excerpt: string | null;
  topic_url: string;
  read_restricted: boolean;
  permission: string | null;
  parent_category_id?: number;
  topic_template: string | null;
  has_children: boolean | null;
  subcategory_count: number | null;
  sort_order: string | null;
  sort_ascending: boolean | null;
  show_subcategory_list: boolean;
  num_featured_topics: number;
  default_view: string | null;
  subcategory_list_style: string;
  default_top_period: string;
  default_list_filter: string;
  minimum_required_tags: number;
  navigate_to_first_post_after_read: boolean;
  custom_fields: Record<string, unknown>;
  allowed_tags: string[];
  allowed_tag_groups: string[];
  allow_global_tags: boolean;
  read_only_banner: string | null;
  form_template_ids: number[];
  auto_close_hours: number | null;
  auto_close_based_on_last_post: boolean;
  group_permissions: unknown[];
  email_in: string | null;
  email_in_allow_strangers: boolean;
  mailinglist_mirror: boolean;
  all_topics_wiki: boolean;
  allow_unlimited_owner_edits_on_first_post: boolean;
  can_delete: boolean;
  allow_badges: boolean;
  topic_featured_link_allowed: boolean;
  search_priority: number;
  default_slow_mode_seconds: number | null;
  uploaded_logo: string | null;
  uploaded_logo_dark: string | null;
  uploaded_background: string | null;
  uploaded_background_dark: string | null;
  required_tag_groups: string[];
  category_setting: {
    auto_bump_cooldown_days: number;
    num_auto_bump_daily: number;
    require_reply_approval: boolean;
    require_topic_approval: boolean;
  };
};

export type TopicWebhook = {
  tags: string[];
  tags_descriptions: Record<string, string>;
  id: number;
  title: string;
  fancy_title: string;
  posts_count: number;
  created_at: string;
  views: number;
  reply_count: number;
  like_count: number;
  last_posted_at: string;
  visible: boolean;
  closed: boolean;
  archived: boolean;
  archetype: string;
  slug: string;
  category_id: number;
  word_count: number;
  deleted_at: string | null;
  user_id: number;
  featured_link: string | null;
  pinned_globally: boolean;
  pinned_at: string | null;
  pinned_until: string | null;
  unpinned: string | null;
  pinned: boolean;
  highest_post_number: number;
  deleted_by: string | null;
  has_deleted: boolean;
  bookmarked: boolean;
  participant_count: number;
  queued_posts_count: number;
  thumbnails: string | null;
  created_by: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
  };
  last_poster: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
  };
  tags_disable_ads: boolean;
  related_topics: unknown[];
  summarizable: boolean;
  discourse_zendesk_plugin_zendesk_id: string | null;
  discourse_zendesk_plugin_zendesk_url: string;
  pending_posts: unknown[];
};

export type PostWebhook = {
  id: number;
  name: string;
  username: string;
  avatar_template: string;
  created_at: string;
  cooked: string;
  post_number: number;
  post_type: number;
  updated_at: string;
  reply_count: number;
  reply_to_post_number: number | null;
  quote_count: number;
  incoming_link_count: number;
  reads: number;
  score: number;
  topic_id: number;
  topic_slug: string;
  topic_title: string;
  category_id: number;
  display_username: string;
  primary_group_name: string | null;
  flair_name: string | null;
  flair_group_id: string | null;
  version: number;
  user_title: string | null;
  reply_to_user?: {
    username: string;
    name: string;
    avatar_template: string;
  };
  bookmarked: boolean;
  raw: string;
  moderator: boolean;
  admin: boolean;
  staff: boolean;
  user_id: number;
  hidden: boolean;
  trust_level: number;
  deleted_at: string | null;
  user_deleted: boolean;
  edit_reason: string | null;
  wiki: boolean;
  reviewable_id: number | null;
  reviewable_score_count: number;
  reviewable_score_pending_count: number;
  topic_posts_count: number;
  topic_filtered_posts_count: number;
  topic_archetype: string;
  category_slug: string;
  akismet_state: string | null;
  user_cakedate: string;
  can_accept_answer: boolean;
  can_unaccept_answer: boolean;
  accepted_answer: boolean;
  topic_accepted_answer: boolean;
};

export type UserWebhook = {
  id: number;
  username: string;
  name: string;
  avatar_template: string;
  email: string;
  secondary_emails: string[];
  last_posted_at: string | null;
  last_seen_at: string | null;
  created_at: string;
  muted: boolean;
  trust_level: number;
  moderator: boolean;
  admin: boolean;
  title: string | null;
  badge_count: number;
  time_read: number;
  recent_time_read: number;
  primary_group_id: number | null;
  primary_group_name: string | null;
  flair_group_id: string | null;
  flair_name: string | null;
  flair_url: string | null;
  flair_bg_color: string | null;
  flair_color: string | null;
  featured_topic: unknown | null;
  bio_excerpt: string | null;
  staged: boolean;
  bio_cooked: string | null;
  pending_count: number;
  profile_view_count: number;
  second_factor_enabled: boolean;
  can_upload_profile_header: boolean;
  can_upload_user_card_background: boolean;
  post_count: number;
  locale: string | null;
  muted_category_ids: number[];
  regular_category_ids: number[];
  watched_tags: string[];
  watching_first_post_tags: string[];
  tracked_tags: string[];
  muted_tags: string[];
  tracked_category_ids: number[];
  watched_category_ids: number[];
  watched_first_post_category_ids: number[];
  system_avatar_template: string;
  muted_usernames: string[];
  can_mute_users: boolean;
  ignored_usernames: string[];
  can_ignore_users: boolean;
  allowed_pm_usernames: string[];
  mailing_list_posts_per_day: number;
  user_notification_schedule: {
    enabled: boolean;
    day_0_start_time: number;
    day_0_end_time: number;
    day_1_start_time: number;
    day_1_end_time: number;
    day_2_start_time: number;
    day_2_end_time: number;
    day_3_start_time: number;
    day_3_end_time: number;
    day_4_start_time: number;
    day_4_end_time: number;
    day_5_start_time: number;
    day_5_end_time: number;
    day_6_start_time: number;
    day_6_end_time: number;
  };
  can_chat_user: boolean;
  cakedate: string;
  birthdate: string | null;
  accepted_answers: number;
  featured_user_badge_ids: number[];
  invited_by: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
  };
  groups: unknown[];
  user_option: {
    user_id: number;
    mailing_list_mode: boolean;
    mailing_list_mode_frequency: number;
    email_digests: boolean;
    email_level: number;
    email_messages_level: number;
    external_links_in_new_tab: boolean;
    color_scheme_id: number | null;
    dark_scheme_id: number | null;
    dynamic_favicon: boolean;
    enable_quoting: boolean;
    enable_smart_lists: boolean;
    enable_defer: boolean;
    digest_after_minutes: number;
    automatically_unpin_topics: boolean;
    auto_track_topics_after_msecs: number;
    notification_level_when_replying: number;
    new_topic_duration_minutes: number;
    email_previous_replies: number;
    email_in_reply_to: boolean;
    like_notification_frequency: number;
    include_tl0_in_digests: boolean;
    theme_ids: number[];
    theme_key_seq: number;
    allow_private_messages: boolean;
    enable_allowed_pm_users: boolean;
    homepage_id: number | null;
    hide_profile_and_presence: boolean;
    hide_profile: boolean;
    hide_presence: boolean;
    text_size: string;
    text_size_seq: number;
    title_count_mode: string;
    bookmark_auto_delete_preference: number;
    timezone: string | null;
    skip_new_user_tips: boolean;
    default_calendar: string;
    oldest_search_log_date: string | null;
    seen_popups: unknown | null;
    sidebar_link_to_filtered_list: boolean;
    sidebar_show_count_of_new_items: boolean;
    watched_precedence_over_muted: boolean | null;
    topics_unread_when_closed: boolean;
    chat_enabled: boolean;
    only_chat_push_notifications: boolean | null;
    ignore_channel_wide_mention: boolean | null;
    show_thread_title_prompts: boolean;
    chat_email_frequency: string;
    chat_header_indicator_preference: string;
    chat_separate_sidebar_mode: string;
  };
};

export type PostLikedWebhook = {
  post: {
    id: number;
    name: string;
    username: string;
    avatar_template: string;
    created_at: string;
    cooked: string;
    post_number: number;
    post_type: number;
    updated_at: string;
    reply_count: number;
    reply_to_post_number: number | null;
    quote_count: number;
    incoming_link_count: number;
    reads: number;
    score: number;
    topic_id: number;
    topic_slug: string;
    topic_title: string;
    category_id: number;
    display_username: string;
    primary_group_name: string | null;
    flair_name: string | null;
    flair_group_id: number | null;
    version: number;
    user_title: string | null;
    bookmarked: boolean;
    raw: string;
    moderator: boolean;
    admin: boolean;
    staff: boolean;
    user_id: number;
    hidden: boolean;
    trust_level: number;
    deleted_at: string | null;
    user_deleted: boolean;
    edit_reason: string | null;
    wiki: boolean;
    reviewable_id: number | null;
    reviewable_score_count: number;
    reviewable_score_pending_count: number;
    topic_posts_count: number;
    topic_filtered_posts_count: number;
    topic_archetype: string;
    category_slug: string;
    akismet_state: string | null;
    user_cakedate: string;
    can_accept_answer: boolean;
    can_unaccept_answer: boolean;
    accepted_answer: boolean;
    topic_accepted_answer: boolean;
  };
  user: {
    id: number;
    username: string;
    name: string;
    avatar_template: string;
  };
};

export type UserBadgeWebhook = {
  id: number;
  granted_at: string;
  created_at: string;
  post_id: number;
  post_number: number;
  badge_id: number;
  user_id: number;
  granted_by_id: number;
  topic_id: number;
};
