import { cn } from "@conquest/ui/cn";
import "@conquest/ui/globals.css";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Conquest App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("h-dvh overflow-hidden", GeistSans.className)}>
        {children}
      </body>
    </html>
  );
}
