import { cn } from "@conquest/ui/cn";
import "@conquest/ui/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const Telegraf = localFont({
  src: [
    {
      path: "../fonts/PPTelegraf-Regular.otf",
      weight: "400",
      style: "medium",
    },
    {
      path: "../fonts/PPTelegraf-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-telegraf",
});

const Suisse = localFont({
  src: [
    {
      path: "../fonts/SuisseIntl-Medium.otf",
      weight: "400",
      style: "medium",
    },
    {
      path: "../fonts/SuisseIntl-Regular.otf",
      weight: "400",
      style: "regular",
    },
  ],
  variable: "--font-suisse",
});

export const metadata: Metadata = {
  title: "Conquest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-dvh font-sans",
          Telegraf.variable,
          Suisse.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
