import { Providers } from "@/providers/Providers";
import { cn } from "@conquest/ui/cn";
import "@conquest/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conquest App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("h-dvh overflow-hidden", inter.className)}>
        <Providers>{children}</Providers>
        <Script
          id="initMap"
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env
            .GOOGLE_API_KEY!}&libraries=places`}
        />
      </body>
    </html>
  );
}
