import type { Plan } from "./types";

export const plans = [
  {
    name: "EXPLORER",
    description: "For small communities",
    priceMonthly: 34,
    priceAnnually: 29,
    priceIdMonthly: "price_1R3JRgCa7sC12ar1IGHNN0yF",
    priceIdAnnually: "price_1R3JRrCa7sC12ar1QDd1Bytj",
    seats: "1 seat",
    members: "Up to 5,000 members",
    integrations: "1 integration",
    api: true,
    popular: false,
  },
  {
    name: "ACTIVE",
    description: "For active communities",
    priceMonthly: 69,
    priceAnnually: 59,
    priceIdMonthly: "price_1R3JSFCa7sC12ar1rxPAFqGE",
    priceIdAnnually: "price_1R3JSOCa7sC12ar1B7u13ua9",
    seats: "2 seats",
    members: "Up to 30,000 members",
    integrations: "3 integrations",
    api: true,
    popular: true,
  },
  // {
  //   name: "CONTRIBUTOR",
  //   description: "For scaling communities",
  //   priceMonthly: 299,
  //   priceAnnually: 254,
  //   priceIdMonthly: "price_1R3JSnCa7sC12ar1BOXtmeyB",
  //   priceIdAnnually: "price_1R3JSxCa7sC12ar1VLgC23zc",
  //   seats: "5 seats",
  //   members: "Up to 100,000 members",
  //   integrations: "5 integrations",
  //   api: true,
  //   popular: false,
  // },
  {
    name: "AMBASSADOR",
    description: "For large communities",
    priceMonthly: "Custom",
    priceAnnually: "Custom",
    priceIdMonthly: "custom_monthly_priceId",
    priceIdAnnually: "custom_annually_priceId",
    seats: "Custom seats",
    members: "Custom members",
    integrations: "Unlimited",
    api: true,
    popular: false,
  },
];

export const plansFeatures: Plan[] = [
  {
    name: "EXPLORER",
    priceMonthly: 34,
    priceAnnually: 29,
    seats: 1,
    members: "Up to 5,000",
    integrations: {
      count: 1,
      community: true,
      github: true,
      api: true,
      socials: false,
      events: false,
    },
    features: {
      memberLevel: true,
      tags: "Unlimited",
      lists: "Unlimited",
      activityTypes: "Unlimited",
    },
  },
  {
    name: "ACTIVE",
    priceMonthly: 69,
    priceAnnually: 59,
    seats: 2,
    members: "Up to 30,000",
    integrations: {
      count: 3,
      community: true,
      github: true,
      api: true,
      socials: true,
      events: true,
    },
    features: {
      memberLevel: true,
      tags: "Unlimited",
      lists: "Unlimited",
      activityTypes: "Unlimited",
    },
  },
  // {
  //   name: "CONTRIBUTOR",
  //   priceMonthly: 299,
  //   priceAnnually: 254,
  //   seats: 5,
  //   members: "Up to 100,000",
  //   integrations: {
  //     count: 5,
  //     community: true,
  //     github: true,
  //     api: true,
  //     socials: true,
  //     events: true,
  //   },
  //   features: {
  //     memberLevel: true,
  //     tags: "Unlimited",
  //     lists: "Unlimited",
  //     activityTypes: "Unlimited",
  //   },
  // },
  {
    name: "AMBASSADOR",
    priceMonthly: "Custom",
    priceAnnually: "Custom",
    seats: "Custom",
    members: "Custom",
    integrations: {
      count: "Unlimited",
      community: true,
      github: true,
      api: true,
      socials: true,
      events: true,
    },
    features: {
      memberLevel: true,
      tags: "Unlimited",
      lists: "Unlimited",
      activityTypes: "Unlimited",
    },
  },
];
