import { auth } from "@/auth";
import { env } from "@conquest/env";
import { cn } from "@conquest/ui/cn";
import "@conquest/ui/globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import Script from "next/script";
import { Providers } from "providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Conquest App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("h-dvh overflow-hidden", inter.className)}>
        <SessionProvider session={session}>
          <Providers>{children}</Providers>
        </SessionProvider>
        <Script
          id="initMap"
          strategy="beforeInteractive"
          src={`https://maps.googleapis.com/maps/api/js?key=${env.GOOGLE_API_KEY}&libraries=places&loading=async`}
        />
      </body>
    </html>
  );
}
